### PR TITLE
Bump temporal sdk and server to v1.19.0

### PR DESCRIPTION
**Pull request by anth0d**
**What changed?** This bumps the Temporal `sdk` and `server` packages to v1.19.0.

**Why?** The Temporal SDK has made a breaking change to its `NewServer` interface, and as such consumers of `temporalite` are unable to use it with the latest Temporal SDK.

**How did you test it?** Ran unit tests locally.

**Potential risks** I am not a temporalite expert, only a user who was motivated to fix this issue to unblock my own work.

**Is hotfix candidate?** No, although the presence of upstream breaking changes and unstable cross-package dependencies which impact the community may suggest there is additional work here for the temporalio maintainers' release processes.

In case it helps, here's an example of a breaking change that affects SDK consumers, this removal ([proto](https://github.com/temporalio/api/compare/f5806628be5c5c5dd26567fc8f8ee6a00c64ccc8...633dd5b3368a272e84592d225bc3df97c518ec28#diff-1c66159704ad8ab03a2814aff0615ff27d695cb8af3833827025074feb623c88L753), [go](https://github.com/temporalio/api-go/commit/2804f1f2b8e090f610e8b342a874af9eaea49a4b#diff-c622c089d94de4c757481e2af1a2bb7484cef4e77d3091301da1cabb9a2a921aL170)) of `EVENT_TYPE_WORKFLOW_UPDATE_REQUESTED` used by `go.temporal.io/server@v1.18.1` was made in a non-breaking manner. Could consider enabling breaking change detection or adding proto fields rather than renaming (breaking) them.

### CODE REVIEW

**Comment by anth0d** [comment]
Note that this also addresses the following pull requests:
* https://github.com/temporalio/temporalite/pull/177
* https://github.com/temporalio/temporalite/pull/181

**Review by cretz — APPROVED** [review]

**Comment by cretz** [comment]
I have asked the server team. I am re-running in the meantime to see if it occurs again.

**Comment by cretz** [comment]
@yycptt has said that, while we will fix these in v1.19.1, for now these dynamic config values will solve the CI issues:

```
history.timerProcessorEnablePriorityTaskScheduler: false
history.transferProcessorEnablePriorityTaskScheduler: false
history.visibilityProcessorEnablePriorityTaskScheduler: false
```

I would have to see how difficult it would be to set these in tests (only to be removed in v1.19.1). cc @jlegrone for thoughts

**Comment by yycptt** [comment]
The panic in the CI should only happen during service shutdown and has no really impact. The reason it happens is that 1.19 defaults to use host level worker pool for task processing, which is shutdown after our persistence layer. and sql persistence layer will encounter NPE (https://github.com/temporalio/temporal/blob/master/common/persistence/sql/factory.go#L191) if there's any new request goes into it after it is closed. 

Regarding ^ dynamic config values, if we want to change it to false, plz only do it for CI and not when actually running the service. Enabling host level pool (which is required for running new multi-cursor queue processing logic) is an important goal for 1.19 and will fix many issues we previously seen in task processing.

**Pull request merged**
